# Generated by Django 3.2.13 on 2022-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://codeinstitute.s3.amazonaws.com/ReactEssentials/DRF/Images/default_post.jpg', upload_to='images/'),
        ),
    ]
